name: Tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Testing
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: 12.x

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm test

  publish:
    needs: build
    # Job name is Greeting
    name: Publish
    # This job runs on Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - run: npm run test
      - run: npm test
      - name: Publish
        run: echo '123'
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'